[package]
name = "mint"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
thiserror.workspace = true
dynamic-nft.workspace = true
cfg-if.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio.workspace = true
