[package]
name = "dynamic-nft-wasm"
version = "0.1.0"
description = "Dynamic NFT - WASM Bindings"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
kaizen.workspace = true
dynamic-nft.workspace = true
workflow-panic-hook.workspace = true
